name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm@latest
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test -- --run

      - name: Build package
        run: pnpm build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
